import "./globals.css";
import Header from "../components/header";
import { NavProvider } from "../context/NavContext";
import { Oswald } from "next/font/google";

import { LenisProvider } from "../context/LenisProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={oswald.className}>
          <LenisProvider>
            <NavProvider>
              <Header />
              {children}
            </NavProvider>
          </LenisProvider>
        </div>
      </body>
    </html>
  );
}
